spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop
    username: vitaly
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kazanuniversityvitalytyutikov@gmail.com
    password: skdifgnizjcepkek
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true